### ISSUE TITLE
你好，希望能获取您的联系方式

### ISSUE THREAD

**Issue by iwasjoker** [huzekang/springboot-datax#1]
你好，我试用了一下代码，有些问题想向您咨询一下，希望您抽时间指点指点我

**Comment by zhouhongfa** [comment]
可以邮件联系

**Comment by iwasjoker** [comment]
你好，请问一下有研究集成了hdfswriter和hdfsreader吗？


1048577457@qq.com
 
发件人： zhouhongfa
发送时间： 2019-08-06 15:26
收件人： huzekang/springboot-datax
抄送： iwasjoker; Author
主题： Re: [huzekang/springboot-datax] 你好，希望能获取您的联系方式 (#1)
可以邮件联系

**Comment by zhouhongfa** [comment]
@iwasjoker 还没用过这两个插件，测试过之后再看吧；

**Comment by iwasjoker** [comment]
好的，谢谢您



1048577457@qq.com
 
发件人： zhouhongfa
发送时间： 2019-08-07 09:50
收件人： huzekang/springboot-datax
抄送： iwasjoker; Mention
主题： Re: [huzekang/springboot-datax] 你好，希望能获取您的联系方式 (#1)
@iwasjoker 还没用过这两个插件，测试过之后再看吧；
