### ISSUE TITLE
mysql在哪里配置？？

### ISSUE THREAD

**Issue by 1shi123de1** [huzekang/springboot-datax#2]
项目需要MySQL，没有写在哪里配置？？
打包后虽然可以跑，使用时会报500错误

**Comment by zhouhongfa** [comment]
数据源配置？在 `/datax-web/src/main/resources/application.yml` 下配置数据源

**Comment by 1shi123de1** [comment]
> 数据源配置？在 `/datax-web/src/main/resources/application.yml` 下配置数据源

是的，就是数据源配置。
我配置之后按照里面的url在mysql里建了datax_web数据库，打包后跑了一下发现还是报500错误。。
看了一下日志，发现是数据库datax_web中找不到表。
所以，数据库datax_web中需要什么表？能把建表sql语句发出来吗？
ps: 在网页访问的端口号不是8080，是8066，希望可以把这些写清楚，谢谢！

**Comment by zhouhongfa** [comment]
@1shi123de1 `README` 已更新

**Comment by 1shi123de1** [comment]
> @1shi123de1 `README` 已更新

已成功运行，谢谢！
