### ISSUE TITLE
Suggestions on development

### ISSUE THREAD

**Issue by zhanghaicheng1** [huzekang/springboot-datax#8]
1、datax dynamic parameter configuration
personal suggestion：
  a、Job configuration json with dynamic parameters;
  b、Synchronize the task module, adding a cell frame that can input parameters;
  c、Execute the script to add executable parameters; eg:-p
2、Task status cannot be displayed
personal suggestion：Can be judged by the process return status
3、Timed task
It is a great feat to achieve the above three major functions！expect！

**Comment by zhouhongfa** [comment]
已实现动态参数配置，见 [update: 实现动态参数配置](https://github.com/huzekang/springboot-datax/commit/a87c9e9d4a96fd1e31b626f328923c84fc72c6b3)

**Comment by zhanghaicheng1** [comment]
感谢前辈百忙之中增加的新功能！👍👍👍👍
